# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run webdriver tests

on:
  workflow_dispatch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2
      with:
        selenoid-start-arguments: |
          --browsers 'chrome' --last-versions 1
    - uses: actions/checkout@v2
    - name: Switch to Node.js 14.17.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.0
    - name: Run tests
      run: npm cit  